[package]
name = "passworm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whoami = "1.4.0"
magic-crypt = "3.1.12"
clap = { version = "4.2.3", features = ["derive"] }
